// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0D9kzx6FrDLqXoQgT_IfJFRMkAv2iBsM',
    appId: '1:456266403040:android:93b73ee2f6aaa7bf671485',
    messagingSenderId: '456266403040',
    projectId: 'cs310termproject',
    databaseURL: 'https://cs310termproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cs310termproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu9THX7uo7QLVQsdLd7MHQtONn1N-q1B4',
    appId: '1:456266403040:ios:329f43b9b5dd8d41671485',
    messagingSenderId: '456266403040',
    projectId: 'cs310termproject',
    databaseURL: 'https://cs310termproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cs310termproject.appspot.com',
    iosClientId: '456266403040-usmge204u1tso1l6fl9pun8qfuqlb0mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cs310TermProject',
  );
}
